
string myfirstName='Lokman';
string myLastName='Kılıç';
string myFullName= myfirstName+'  '+myLastName;
System.debug('My Full Name is '+ myFullName);

string brandCar='Audi ';
system.debug(brandCar);
string modelCar= 'Q7' ;
system.debug(modelCar);
string colorCar= 'Light Blue';
system.debug(colorCar);
string MyCar= brandCar+' '+ modelCar +' '+ colorCar;
system.debug('Features of my car=>'+MyCar);




