public class SalesforceDeveloper{
    
    public void myFirstCode(){

    string myFavoritCountry='My Favorite country is London';
    system.debug(myFavoritCountry);
    string myFavoritFilm=' My Favorite film is  The Good, The Bad and The Uggly';
    system.debug(myFavoritFilm);
    string myFavoritSession='My Favorite session is  Summer'; 
    system.debug(myFavoritSession);
  }   
    
    
    
    
    public void myFavorites() {
        string myCountry='Stuttgart';
        system.debug(myCountry);
        integer myFavoritNumber=1522;
        system.debug(myFavoritNumber);
        system.debug('My Country is '+myCountry +  ','+ ' My favorite number is ' + myFavoritNumber );
        

    }
}
