



public  class StudentMarksheet {
   
          
        public void showMarksheetUsingDatatype(){
            
            String  firstName='Burak';
            string lastName='Yusuf';
            Integer  mathematics=90;
            Integer  english=75;
            Integer chemistry=80;
            System.debug('My Full Name is '+firstName+lastName );
            System.debug('My English grade is '+english );
            System.debug('My Mathematics grade is '+mathematics );
            System.debug('My chemistry grade is '+chemistry );        
     
     
        }


        public void showMarksheetUsingObject(){

            Object firstName1='Burak';
            Object lastName1='Yusuf';
            Object  mathematics1=90;
            Object  english1=75;
            Object  chemistry1=80;
            System.debug('My Full Name is '+firstName1+lastName1);
            System.debug('My English grade is '+english1);
            System.debug('My Mathematics grade is '+mathematics1);
            System.debug('My chemistry grade is '+chemistry1 );
            
                     

        }
    }

