list<integer> listInteger = new List<Integer>();
listInteger.add(10); //0
listInteger.add(15); //1
listInteger.add(21); //2
listInteger.add(15); //3
listInteger.add(12); //4
listInteger.add(18); //5

integer sum = Calculator3.add(listInteger);
system.debug('sum -> ' + sum);

/*
listString.add('Lokman');
listString.add('Ejder');
listString.add('Hasan');

//string aile=Calculator3.lok(listString);
system.debug(Calculator3.lok(listString));

system.debug('aile ' + listString);
*/


